[pytest]
DJANGO_SETTINGS_MODULE = config.settings
addopts =
    --strict-markers
    ; display reasons for all except passed
    -ra
    ; reuse test db between test runs
    ; use --create-db to force creation
    --reuse-db

xfail_strict = true
